In [2]:
df=pd.read_excel("E:\HTL Project\HTL Raw data.xlsx")
df.head()

<IPython.core.display.Javascript object>

Feedstock        Type  Moisture  Volatile   Ash  Proteins   \
0     Spirulina platensis  microalgae      11.8      67.0   8.6       53.0   
1         Nannochloropsis  microalgae       3.9      67.4  24.4       52.0   
2      Chlorella vulgaris  microalgae       5.8      67.3   9.5       49.5   
3  Porphyridium purpureum  microalgae       8.5      61.6  18.5       45.6   
4  Dunaliella tertiolecta  microalgae       4.9      54.4  13.5       34.0   

   lipids   carbohydrates    C      H  ...     O    S  Culture Condition  \
0      7.5           11.0  72.7   8.8  ...  11.5  0.6          open pond   
1     14.0           27.0  76.0  10.3  ...   9.0  0.8              Flask   
2     11.0           14.2  70.6   9.2  ...  12.3  0.4          open pond   
3     12.1            NaN  69.1   8.4  ...  15.2  0.5                PBR   
4     23.0           21.0  72.0   8.8  ...   9.9  0.3                NaN   

  Catalyst Temp  Time  Pressure   HHV   ERR  Yield%  
0   Na2CO3  300    30       130  35.2  37.2    36.0  
1   H-ZSM5  350    60       180  37.9  42.7    43.0  
2     LiOH  250    60       100  33.8  33.0    33.0  
3      NaN  250    30       100  34.8  41.5    24.7  
4   Na2CO3  375    50       221  36.0  64.8    55.3  

[5 rows x 21 columns]

In [3]:
df.columns

Index(['Feedstock', 'Type', 'Moisture', 'Volatile', 'Ash', 'Proteins ',
       'lipids ', 'carbohydrates', 'C ', 'H', 'N', 'O', 'S',
       'Culture Condition', 'Catalyst', 'Temp', 'Time', 'Pressure', 'HHV',
       'ERR', 'Yield%'],
      dtype='object')

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [5]:
df['Feedstock']=le.fit_transform(df['Feedstock'])
df['Type']=le.fit_transform(df['Type'])
df['Culture Condition']=le.fit_transform(df['Culture Condition'])
df['Catalyst']=le.fit_transform(df['Catalyst'])

In [6]:
df.head()

Feedstock  Type  Moisture  Volatile   Ash  Proteins   lipids   \
0         21     1      11.8      67.0   8.6       53.0      7.5   
1         10     1       3.9      67.4  24.4       52.0     14.0   
2          3     1       5.8      67.3   9.5       49.5     11.0   
3         12     1       8.5      61.6  18.5       45.6     12.1   
4          7     1       4.9      54.4  13.5       34.0     23.0   

   carbohydrates    C      H  ...     O    S  Culture Condition  Catalyst  \
0           11.0  72.7   8.8  ...  11.5  0.6                  3        14   
1           27.0  76.0  10.3  ...   9.0  0.8                  0         7   
2           14.2  70.6   9.2  ...  12.3  0.4                  3        11   
3            NaN  69.1   8.4  ...  15.2  0.5                  1        22   
4           21.0  72.0   8.8  ...   9.9  0.3                  4        14   

   Temp  Time  Pressure   HHV   ERR  Yield%  
0   300    30       130  35.2  37.2    36.0  
1   350    60       180  37.9  42.7    43.0  
2   250    60       100  33.8  33.0    33.0  
3   250    30       100  34.8  41.5    24.7  
4   375    50       221  36.0  64.8    55.3  

[5 rows x 21 columns]

In [16]:
df['Moisture']=df['Moisture'].fillna(df['Moisture'].mode()[0])
df['Volatile']=df['Volatile'].fillna(df['Volatile'].mode()[0])
df['carbohydrates']=df['carbohydrates'].fillna(df['carbohydrates'].mode()[0])
df['S']=df['S'].fillna(df['S'].mode()[0])
df['ERR']=df['ERR'].fillna(df['ERR'].mode()[0])
df['lipids ']=df['lipids '].fillna(df['lipids '].mode()[0])

In [17]:
df.isna().sum()

Feedstock            0
Type                 0
Moisture             0
Volatile             0
Ash                  0
Proteins             0
lipids               0
carbohydrates        0
C                    0
H                    0
N                    0
O                    0
S                    0
Culture Condition    0
Catalyst             0
Temp                 0
Time                 0
Pressure             0
HHV                  0
ERR                  0
Yield%               0
dtype: int64

# All Features VS Yield%

In [20]:
x=df.drop('Yield%',axis=1)
y=df['Yield%']

In [21]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
reg=linear_model.LinearRegression()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [22]:
reg.fit(x_train,y_train)

LinearRegression()

In [23]:
y_pred = reg.predict(x_test)
y_pred

array([19.04317502, 15.2429464 , 44.57909699, 42.45036848, 18.40935579,
       28.06121263, 36.23336937, 38.44565526, 25.80085286, 39.86871773,
       17.11529553, 35.68303631, 32.28792477, 44.46431929, 39.3034442 ,
       30.70042101, 29.53201096, 21.15565301, 44.96216136, 41.73824086,
       38.53964831, 37.74516522, 28.63203115, 41.81246764, 36.69745498,
       13.61179153, 31.06864692, 23.73809565, 25.33418429, 18.64987652])

In [24]:
from sklearn.metrics import r2_score

In [26]:
print("Mean absolute Error: " ,np.mean(np.absolute(y_pred-y_test)))
print("Root mean square error: " ,np.mean(y_pred-y_test)**2)
print("R2 square: " ,r2_score(y_pred,y_test))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Mean absolute Error:  5.168603487304768


<IPython.core.display.Javascript object>

Root mean square error:  0.3759071411578253
R2 square:  0.47705334883120076


# All Features Vs HHV

In [27]:
x=df.drop('HHV',axis=1)
y=df['HHV']

In [31]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
reg=linear_model.LinearRegression()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [32]:
reg.fit(x_train,y_train)

LinearRegression()

In [33]:
y_pred = reg.predict(x_test)
y_pred

array([14.38441704, 26.9855167 , 29.55889917, 24.2284871 , 25.95647566,
       36.20174281, 24.93509284, 11.2663543 , 35.19247518, 28.96782497,
       32.13877876, 34.24258998, 35.14703698, 35.33596261, 23.90017525,
       25.24583721, 25.91913752, 34.45876658, 29.15870948, 24.94811411,
       34.68411518, 24.02574399, 11.0614097 , 33.85746503, 11.07741449,
       29.28196968, 25.00118164, 35.66787053, 34.72258352, 38.24369531])

In [34]:
print("Mean absolute Error: " ,np.mean(np.absolute(y_pred-y_test)))
print("Root mean square error: " ,np.mean(y_pred-y_test)**2)
print("R2 square: " ,r2_score(y_pred,y_test))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Mean absolute Error:  0.33798762947364647


<IPython.core.display.Javascript object>

Root mean square error:  0.016936043910403663
R2 square:  0.9893807688509063


# All Features Vs ERR

In [40]:
x=df.drop('ERR',axis=1)
y=df['ERR']

In [41]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
reg=linear_model.LinearRegression()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [42]:
reg.fit(x_train,y_train)

LinearRegression()

In [43]:
y_pred = reg.predict(x_test)
y_pred

array([17.92912649, 16.49706363, 37.61983217, 20.76494024, 48.79971196,
       21.59993237, 38.97682962, 15.88371528, 30.63607306, 21.07529794,
       14.49731849, 28.25261347, 35.63082408,  7.58307733, 24.10922914,
       37.70447554, 20.86287788, 19.14450189, 31.69762165, 16.95560674,
       28.03737714, 13.54928847, 17.40585125, 16.37030329, 17.18919823,
       23.67998931, 37.76521549, 28.884369  , 40.87026024, 38.92300142])

In [44]:
print("Mean absolute Error: " ,np.mean(np.absolute(y_pred-y_test)))
print("Root mean square error: " ,np.mean(y_pred-y_test)**2)
print("R2 square: " ,r2_score(y_pred,y_test))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Mean absolute Error:  5.760032629524907


<IPython.core.display.Javascript object>

Root mean square error:  2.0644399477601536
R2 square:  0.40812736041854925
